spring:
  application:
    name: "currency-conversion-service"
  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile:
server:
  port: 8100
springdoc:
  api-docs:
    path: "currency-conversion-service"
eureka:
  instance:
    hostname: 'localhost'
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'