spring:
  application:
    name: "currency-conversion-service"
  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile:
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8100
springdoc:
  api-docs:
    path: "currency-conversion-service"
eureka:
  instance:
    hostname: 'localhost'
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
logging:
  pattern:
    console: '[%p] %d{yyyy-MM-dd HH:mm:ss} [THREAD - %t] %-5p %c:%L - %m%n'
    file: '[%p] %d{yyyy-MM-dd HH:mm:ss} [THREAD - %t] %-5p %c:%L - %m%n'