spring:
  application:
    name: "currency-exchange-service"
  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
server:
  port: 8000
springdoc:
  api-docs:
    path: "currency-exchange-service"
eureka:
  instance:
    hostname: 'localhost'
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
resilience4j:
  retry:
    instances:
      sample-api:
        maxRetryAttempts: 5
        waitDuration: 1s
        enableExponentialBackoff: true